### ISSUE TITLE
Failed to load the graphql-autocomplete package

### ISSUE THREAD

**Issue by vitexikora** [orionsoft/atom-graphql-autocomplete#20]
[Enter steps to reproduce:]

1. Update to version 1.3.0 (from 1.1.0)
2. Error on every Atom launch

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [graphql-autocomplete](https://github.com/nicolaslopezj/atom-graphql-autocomplete) package 1.3.0

### Stack Trace

Failed to load the graphql-autocomplete package

```
At regeneratorRuntime is not defined

ReferenceError: regeneratorRuntime is not defined
    at /packages/graphql-autocomplete/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:69:7
    at /packages/graphql-autocomplete/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:193:6
    at /packages/graphql-autocomplete/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:451:2)
    at /packages/graphql-autocomplete/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:454:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/graphql-autocomplete/node_modules/graphql-language-service-interface/dist/index.js:103:31)
    at /packages/graphql-autocomplete/node_modules/graphql-language-service-interface/dist/index.js:104:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/graphql-autocomplete/lib/Snippets/getSnippets.js:11:40)
    at /packages/graphql-autocomplete/lib/Snippets/getSnippets.js:54:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/graphql-autocomplete/lib/Snippets/index.js:13:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
autocomplete-modules 1.12.0 
busy-signal 1.4.3 
convert-file-encoding 0.1.0 
docblockr 0.13.7 
Fast_Duplicate 1.2.0 
git-log 0.4.1 
graphql-autocomplete 1.3.0 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.14.2 
js-hyperclick-project-path 1.12.0 
language-babel 2.85.0 
language-graphql 1.0.0 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
react 0.18.0 
react-snippets 1.1.1 
split-diff 1.5.3 
Sublime-Style-Column-Selection 1.7.5 
sync-settings 0.8.6 
tabs-to-spaces 1.0.5 
yui-doc-snippets 0.1.0 
```

**Comment by tgrrr** [comment]
Same error:

Non-Core Packages:

```
Hydrogen@2.12.0
atom-beautify@0.33.4
atom-increment@0.3.4
atom-inline-blame@0.0.7
atom-jump-block@0.5.4
atom-math@0.0.9
atom-notes@1.20.0
docblock-python@0.15.0
es6-javascript@1.0.0
es6-react-redux-snippets@3.9.0
file-icons@2.1.35
hey-pane@1.2.0
hydrogen-launcher@1.2.2
hyperclick@0.1.5
js-hyperclick@1.13.3
js-refactor@0.8.1
kite@0.172.0
language-atom-notes@0.4.1
language-graphql@1.0.0
language-javascript-jsx@0.3.7
language-latex@1.2.0
language-mdx@0.1.0
language-r@0.4.2
language-todo-extra-words@0.2.0
latex@0.50.2
linter@2.3.1
linter-eslint@8.5.5
linter-pylint@2.1.1
markdown-preview-enhanced@0.16.3
markdown-table-editor@1.1.2
open-file@1.4.0
preview-inline@1.5.1
python-tools@0.6.9
rainbow-csv@0.3.1
react@0.18.0
react-snippets@1.1.3
sort-lines@0.19.0
split-diff@1.6.0
sync-settings@0.8.6
teletype@0.13.4
todo-show@2.3.2
tree-view-copy-relative-path@1.2.0
```
