### ISSUE TITLE
Version 1.03 with Atom 1.19 breaks

### ISSUE THREAD

**Issue by ccuilla** [orionsoft/atom-graphql-autocomplete#9]
Getting these errors since updating to Atom 1.19 (macOS):

```
LinterError TypeError: Cannot read property 'join' of undefined
    at Linter.<anonymous> (/Users/chris/.atom/packages/graphql-autocomplete/lib/Linter/index.js:57:46)
    at Generator.next (<anonymous>)
    at step (/Users/chris/.atom/packages/graphql-autocomplete/lib/Linter/index.js:9:273)
    at /Users/chris/.atom/packages/graphql-autocomplete/lib/Linter/index.js:9:443
    at Linter.<anonymous> (/Users/chris/.atom/packages/graphql-autocomplete/lib/Linter/index.js:9:99)
    at promises.push.Promise.then._this2.emitter.emit.number (/Users/chris/.atom/packages/linter/lib/linter-registry.js:101:24)
    at _loop (/Users/chris/.atom/packages/linter/lib/linter-registry.js:99:21)
    at LinterRegistry.<anonymous> (/Users/chris/.atom/packages/linter/lib/linter-registry.js:87:40)
    at Generator.next (<anonymous>)
    at LinterRegistry.<anonymous> (/Users/chris/.atom/packages/linter/lib/linter-registry.js:143:4)
    at Generator.next (<anonymous>)
    at step (/Users/chris/.atom/packages/linter/lib/linter-registry.js:5:273)
    at /Users/chris/.atom/packages/linter/lib/linter-registry.js:5:443
    at LinterRegistry.<anonymous> (/Users/chris/.atom/packages/linter/lib/linter-registry.js:5:99)
    at /Users/chris/.atom/packages/linter/lib/main.js:125:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Users/chris/.atom/packages/linter/lib/editor-linter.js:32:22
    at later (/Users/chris/.atom/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

```
Uncaught (in promise) TypeError: Cannot read property '4' of undefined
    at Snippets.getLine (/Users/chris/.atom/packages/graphql-autocomplete/lib/Snippets/index.js:13:31)
    at Snippets.<anonymous> (/Users/chris/.atom/packages/graphql-autocomplete/lib/Snippets/index.js:17:27)
    at Generator.next (<anonymous>)
    at step (/Users/chris/.atom/packages/graphql-autocomplete/lib/Snippets/index.js:9:273)
    at /Users/chris/.atom/packages/graphql-autocomplete/lib/Snippets/index.js:9:443
    at Snippets.<anonymous> (/Users/chris/.atom/packages/graphql-autocomplete/lib/Snippets/index.js:9:99)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

**Comment by nicolaslopezj** [comment]
Fixed in 1.0.4
